version: "2"
services:
  app:
    build: app
    image: test-app
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  mongo:
    build: mongo
    image: test-mongo
    ports:
      - "27017"
    logging:
      driver: none
  redis:
    build: redis
    image: test-redis
    ports:
      - "6379"
    logging:
      driver: none
